micronaut:
  application:
    name: micronautguide
---
#tag::datasource[]
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    schema-generate: CREATE_DROP
    dialect: MYSQL
#end::datasource[]
---
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true
#end::flyway[]